catlog/urls.py
from django.urls import path

from . import views

app_name = "catlog"

urlpatterns = [
    # Url for the detail view of the product
    path("<int:product_id>/", views.detail, name='detail'),
    # Url for the search view
    path("search/", views.search, name='search'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views as users_view
from users.forms import UserLoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('register/', users_view.register, name='register'),
    path('profile/', users_view.profile, name='profile'),
    path('user_search/', users_view.listing, name='user_search'),
    path('catalogue/', include('catlog.urls', namespace='catlog')),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='users/login.html', authentication_form=UserLoginForm
        ),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='users/logout.html'),
        name='logout',
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="pages-home"),
    path("mentions", views.mentions, name="pages-mentions"),
]

catlog/models.py
from django.db import models

NUTRITION_GRADES = ['a', 'b', 'c', 'd', 'e']


# Create your models here.
class Category(models.Model):
    """Class managing any element regarding category object.

    Args:
        models ([type]): [description]

    Returns:
        Category: Return an object of type Category
    """

    code = models.TextField(unique=True)
    name = models.TextField()
    url = models.TextField()
    active = models.BooleanField(default=True)

    def __str__(self):
        """Return the name of category instead of technical description.

        Returns:
            String: Name of the category
        """
        return self.name


class Store(models.Model):
    """Class managing any element regarding store object.

    Args:
        models ([type]): [description]

    Returns:
        Store: Return an object of type Store
    """

    code = models.TextField(unique=True)
    name = models.TextField()
    url = models.TextField()
    active = models.BooleanField(default=True)

    def __str__(self):
        """Return the name of brand instead of technical description.

        Returns:
            String: Name of the store
        """
        return self.name


class Brand(models.Model):
    """Class managing any element regarding brand object.

    Args:
        models ([type]): [description]

    Returns:
        Brand: Return an object of type Brand
    """

    code = models.TextField(unique=True)
    name = models.TextField()
    url = models.TextField()
    active = models.BooleanField(default=True)

    def __str__(self):
        """Return the name of brand instead of technical description.

        Returns:
            String: Name of the brand
        """
        return self.name


class Product(models.Model):
    """[Class managing any element regarding product object]

    Args:
        models ([type]): [description]

    Returns:
        [Product]: [Return an object of type Product]
    """

    code = models.TextField(unique=True)
    name = models.TextField()
    nutrition_grade_fr = models.TextField()
    quantity = models.TextField()
    ingredients_text = models.TextField(default='no descripton')
    ingredients_text_with_allergens_fr = models.TextField(
        default='no descripton'
    )
    url = models.TextField()
    url_images = models.TextField()
    active = models.BooleanField(default=True)
    categories = models.ManyToManyField(
        Category, related_name='products', blank=True
    )
    stores = models.ManyToManyField(Store, related_name='products', blank=True)
    brands = models.ManyToManyField(Brand, related_name='products', blank=True)

    def __str__(self):
        """Return the name of product instead of technical description.

        Returns:
            String: Name of the product
        """
        return self.name

    def get_recommanded_products(self):
        """Get the list of recommanded products according the nutrition grade
        of the current product. Only products having same grade or better are
        part of the results.

        Returns:
            List: List of products
        """
        products = []
        for product in Product.objects.filter(
            categories=self.categories.values()[0]['id']
        ):
            if NUTRITION_GRADES.index(
                product.nutrition_grade_fr
            ) <= NUTRITION_GRADES.index(self.nutrition_grade_fr):
                products.append(product)
        return products

catlog/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import redirect, render

from users.models import User, UserProductsSearch

from .models import Product


def detail(request, product_id):
    """Accordingv the requesting, getting the information for a given product.

    Args:
        request (request): Incoming request
        product_id (integer): technical id of the product

    Returns:
        view: return the view according the product info
    """
    product = Product.objects.get(pk=product_id)
    context = {
        'product': product,
        'product_categories': product.categories.all(),
        'product_stores': product.stores.all(),
        'product_brands': product.brands.all(),
        'nutriscore_image': 'dist/assets/img/nutri/Nutri-score-{0}.png'.format(
            product.nutrition_grade_fr.upper()
        ),
    }
    print(context)
    return render(request, 'catlog/detail.html', context)


def search(request):
    """ If the request is type Get
    According the user request retrieve the product.
    if no match : User is notified that there is no results
    if more than one match : User is notified that the user has to refine
    his or her request.
    if one match : Get the product and then get the list of recommanded
    products associated with.

    If the request is type Post
    Saving the selected product

    Args:
        request (request): [description]

    Returns:
        [type]: Return the context to display.
    """

    if request.method == 'GET':

        query = request.GET.get('query')
        products = []
        context = {
            'products': [],
            'title': "",
            'query': query,
            'paginate': True,
            'picture_head': None,
            'perfect_match': False,
            'product': None,
        }
        # In those cases we display the catalogue page
        if (
            not query
            or len(Product.objects.filter(name__icontains=query)) == 0
        ):
            products = []
            context['title'] = "Pas de résultat pour %s" % query
            context['products'] = products
            return render(request, 'catlog/search.html', context)
        # In this case user has to refine his or her request
        if len(Product.objects.filter(name__icontains=query)) > 1:
            products = []
            context['title'] = (
                "Trop de résultats pour %s. Affinez votre recherche" % query
            )
        # In returning the found product and recommanded products associated
        #  with
        elif len(Product.objects.filter(name__icontains=query)) == 1:
            temp_list = Product.objects.filter(name__icontains=query)
            product = Product.objects.get(pk=temp_list[0].id)
            products = product.get_recommanded_products()
            context['picture_head'] = product.url_images
            context['perfect_match'] = True
            context['title'] = "%s" % query.upper()
            paginator = Paginator(products, 6)
            # Get current page number
            page = request.GET.get('page')
            try:
                # Return only this page albums and not others
                products = paginator.page(page)
            except PageNotAnInteger:
                # If page is not an integer, deliver first page.
                products = paginator.page(1)
            except EmptyPage:
                # If page is out of range (e.g. 9999), deliver last page
                #  of results.
                products = paginator.page(paginator.num_pages)
            context['product'] = product
        context['products'] = products

        return render(request, 'catlog/search.html', context)
    # saving the product
    elif request.method == 'POST':
        subproduct = Product.objects.get(
            id=int(request.POST.get('subproductid'))
        )
        user = User.objects.get(id=int(request.POST.get('userid')))
        product = Product.objects.get(id=int(request.POST.get('productid')))
        if (
            len(
                UserProductsSearch.objects.filter(
                    user=user, mainProduct=product, subProduct=subproduct
                )
            )
            == 0
        ):
            UserProductsSearch.objects.create(
                user=user, mainProduct=product, subProduct=subproduct
            )
        return redirect(request.POST.get('next'))

catlog/templates/catlog/detail.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<header class="masthead" style="background-image:None ;">
    <div class="row header-div-top" style="background-image: url({{ product.url_images }});" >
        <div class="col-sm-4 offset-sm-4 pt-5 align-items-center justify-content-center text-center color-primary">
            <h2 id="detail_product_name">{{ product.name }}</h2>
        </div> 
    </div>
    <div class="clear"></div>
    <div class="row">
        <div class="col-sm-10  offset-sm-1 col-md-5  offset-md-1 ">
            <img class="img-fluid pt-5" src="{% static nutriscore_image %}" alt=""  id="pict-nutri-score" style="height: 25vh;"/>
        </div>
        <div class="col-sm-10 offset-sm-1 col-md-5 align-items-center justify-content-center text-center color-primary">
            <h3 class="pt-5 pr-3">Repères nutritionels pour 100g </h3>
            <p class="pt-5 pr-3" id="detail_product_ingredients"> {{ product.ingredients_text }} </p>
        </div> 
    </div>
    <div class="clear"></div>
    <div class="row pt-5">
        <div class="col-sm-4 offset-sm-4 pt-5 align-items-center justify-content-center text-center color-primary">
            <a class="ml-2"   href="{{ product.url }}">
                <button type="submit" class="btn btn-primary mb-2 align-items-center justify-content-center text-center" id="detail_product_url">Voire la fiche Open Food Facts</button>
            </a>
        </div> 
    </div>
</header>
{% endblock content %}

catlog/templates/catlog/results_list.html
<!-- Block used to display a list of product with image -->
{% block resultList %}    
    <div class="clear"></div>
    {% if perfect_match %}
    <div class="col-sm-10 offset-sm-1 align-items-center justify-content-center text-center color-primary pt-1 pb-1">
        <h3>Vous pouvez remplacer ce produit par</h3>
    </div>
    <div class="clear"></div>                           
    {% endif %}
    <div class="col-sm-10 offset-sm-1 align-items-center justify-content-center text-center">
        <div class="row">
        <!-- Managing the display of the list of products -->
        {% for sub_product in products %}
            <div class="pt-3 col-sm-12 col-md-4">
                <div class="row">
                    <div class="col-sm-6">
                        <a href="/catalogue/{{ sub_product.id }}"> 
                            <img class="img-fluid pt-3" src="{{ sub_product.url_images }}" alt="No picture"  style="height: 12vh;"/>
                        </a>
                    </div>
                    <div class="col-sm-1 text-right">
                        <h3 style="position: top;" class="color-primary"> {{ sub_product.nutrition_grade_fr }} </h3>
                    </div>
                </div>
                <div class="row">
                    <div class="pt-3 text-center color-primary col-sm-6">
                        {{ sub_product.name }}
                    </div>
                </div>
                <!-- This Div is only displayed when user is connected --> 
                {% if user.is_authenticated %}
                <div class="row text-center">
                    <form class="form-inline" action="{% url 'catlog:search' %}" method="POST">
                    {% csrf_token %}
                        <input type="hidden" name="productid" value="{{ product.id }}">
                        <input type="hidden" name="subproductid" value="{{ sub_product.id }}">
                        <input type="hidden" name="userid" value="{{ user.id }}">
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        <div class="row align-items-center">
                            <button type="submit" class="btn btn-primary mb-2"><i class="fas fa-save" style="color:white;"></i></button>
                            <p class="ml-5 color-primary" style="font-size: bold;">Sauvegarder</p>
                        </div>
                        
                    </form>
                </div>
                {% endif %}      
            </div> 
        {% endfor %}    
        </div>          
    </div>            
    <div class="clearfix"></div>
    <!--Div to manage the pagination --> 
    <div class="col-sm-10 offset-sm-1 align-items-center justify-content-center text-center pt-3" >
        <div class="row align-items-center justify-content-center text-center">
            <nav aria-label="..."> 
                <ul style="list-style: none;" >
                    <div class="row pt-1">
                    {% if products.has_previous %}
                        <h3><li><div class="mr-3"><a href="?{% if query %}query={{query}}&{% endif %}page={{ products.previous_page_number }}">Précédent</a></div></li></h3>
                    {% endif %}
                    {% if products.has_next %}
                        <h3><li class="pl-5" ><div><a href="?{% if query %}query={{query}}&{% endif %}page={{ products.next_page_number }}">Suivant</a></div></li></h3>
                    {% endif %}
                    </div>  
                </ul>  
            </nav>
        </div>
    </div>
{% endblock %} 

catlog/templates/catlog/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Search {% endblock title %}

{% block content %}
<header class="masthead" style="background-image:None ;">
    <div class="row header-div-top mb-3" style=" background-color:black; background-image: url({{picture_head}});" >
        <div class="col-sm-4 offset-sm-4 pt-5 align-items-center justify-content-center text-center color-primary">
            <h2 class="pt-5">Résultats de votre recherche</h2>
            <h2 class="pt-5" id="detail_product_name">{{title}}</h2>
        </div> 
    </div>
    {% block resultList %} 
        {% include 'catlog/results_list.html'%}
    {% endblock %}
</header>
{% endblock content %}